exclude: '^(\.github/|\.vscode/).*|CODE_OF_CONDUCT\.md|CHANGELOG\.md'

repos:
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.3.3
    hooks:
      - id: cspell # Spell check changed files
      - id: cspell # Spell check the commit message
        name: check commit message spelling
        args:
          - --no-must-find-files
          - --no-progress
          - --no-summary
          - --files
          - .git/COMMIT_EDITMSG
        stages: [commit-msg]
        always_run: true # This might not be necessary.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
  # Shell: shfmt
  # - repo: https://github.com/scop/pre-commit-shfmt
  #   rev: v3.7.0-1
  #   hooks:
  #     - id: shfmt
  #       args: [-w, -i, "2"] # Write changes, indent with 2 spaces
  # Python: Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11 # Use the version matching your pyproject.toml
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --config=pyproject.toml]
      # Run the formatter
      - id: ruff-format
        args: [--config=pyproject.toml]
  # Markdown: Markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--config, .github/linters/.markdownlint.json]
  # Shell: ShellCheck
  # - repo: https://github.com/koalaman/shellcheck-precommit
  #   rev: v0.9.0
  #   hooks:
  #     - id: shellcheck
  #       args: ["-e", "SC1091", "-e", "2086"]
  # CSS: Stylelint
  # Requires a .stylelintrc.json in root
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        args: ["--fix", "**/*.css"]
        additional_dependencies:
          - stylelint
          - stylelint-config-standard@20.0.0
          - stylelint-config-prettier
  # CSS: Prettier (Formatting)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: prettier-css
        types: [css]  # Only run on CSS files
        # If you want it to run on EVERYTHING (JS, JSON, MD), remove the 'types' line.
